services:
  main:
    build: ./homepage
    command: npm start
    container_name: growthapp_main
    expose:
      - "3000"
    env_file:
      - ./homepage/.env
    networks:
      - backend
    restart: unless-stopped

  chatgpt:
    build: ./homepage/projects/ChatGPT/auth-app
    command: npm start
    container_name: growthapp_chatgpt
    expose:
      - "3000"
    env_file:
      - ./homepage/.env
    networks:
      - backend
    restart: unless-stopped

  message:
    build: ./homepage/projects/message/auth-app
    command: npm start
    container_name: growthapp_message
    expose:
      - "3000"
    env_file:
      - ./homepage/.env
    networks:
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: growthapp_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BASE_URL=${BASE_URL}
      - MAIN_URL=${MAIN_URL}
      - CHATGPT_URL=${CHATGPT_URL}
      - MESSAGE_URL=${MESSAGE_URL}
    volumes:
      - /var/www/growthapp:/var/www/growthapp:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - main
      - chatgpt
      - message
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
