services:
  main:
    build: ./homepage
    command: npm start
    expose:
      - "3000"
    ports:
      - "3001:3000"   # main dispo sur localhost:3001
    env_file:
      - ./homepage/.env
    networks:
      - backend

  chatgpt:
    build: ./homepage/projects/ChatGPT/auth-app
    command: npm start
    expose:
      - "3000"
    ports:
      - "3002:3000"   # chatgpt dispo sur localhost:3002
    env_file:
      - ./homepage/.env
    networks:
      - backend

  message:
    build: ./homepage/projects/message/auth-app
    command: npm start
    expose:
      - "3000"
    ports:
      - "3003:3000"   # message dispo sur localhost:3003
    env_file:
      - ./homepage/.env
    networks:
      - backend

networks:
  backend:
    driver: bridge